# Generated by Django 2.0.5 on 2018-05-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('club_head', models.CharField(max_length=60)),
                ('club_location', models.CharField(max_length=30)),
                ('club_description', models.TextField(max_length=250)),
            ],
        ),
    ]
